<a href="https://colab.research.google.com/github/leaezequiel/entrega_tp/blob/main/proyecto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pre Entrega: Leandro Stivanello

## Etapa 1: Recopilación y Preparación de Datos
**Clases 1 a 4**

---

## 🎯 Objetivo
Demostrar habilidades en **Python**, familiaridad con el **entorno de Google Colaboratory** y conocimientos básicos sobre **manipulación y análisis de datos**.

Durante esta etapa se trabajará con distintos conjuntos de datos, aplicando estructuras básicas del lenguaje y herramientas de análisis como **Pandas**.
``

## 📌 Actividades

### 1️⃣ Carga de datos en Google Colab

Se crea el entorno de trabajo en Google Colaboratory y se cargan los distintos sets de datos desde Google Drive o enlaces externos, almacenándolos en **DataFrames** para su análisis.

In [ ]:
import pandas as pd

def load_gdrive_csv(file_id, **kwargs):
    url = f"https://drive.google.com/uc?id={file_id}"
    return pd.read_csv(url, **kwargs)

df_ventas = load_gdrive_csv("1jlo-TjeDEkIeHrbcdSVXO8pqzTTfyE6N")
df_clientes = load_gdrive_csv("11-FPOE9X1AvxGE6AUXTCspVQJzrLT_2f")
df_marketing = load_gdrive_csv("1ZSfAcNDyo2eiioc7za_h57lvlm2RtScu")

'''
print(df_ventas)
print(df_clientes)
print(df_marketing)
'''

'\nprint(df_ventas)\nprint(df_clientes)\nprint(df_marketing)\n'


### 4️⃣ Introducción a Pandas – Análisis Exploratorio

Se realiza un análisis exploratorio inicial de los DataFrames, utilizando funciones básicas de Pandas para comprender la estructura y el contenido de los datos.

In [ ]:
#hice un diccionario con cada df para hacerlo una sola vez y ejecutar a todos:
data_frames = {
    "ventas": df_ventas,
    "clientes": df_clientes,
    "marketing": df_marketing
}

#recorri cada clave, y cada valor del diccionario ejecutando las funciones
for nombre, df in data_frames.items():
    print(f"\n--- Análisis de {nombre} ---")
    df.info()
    print(df.describe())
    #print(df.head())
    print("Shape:", df.shape)
    print("Columnas:", df.columns)

--- Análisis de ventas ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035 entries, 0 to 3034
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_venta     3035 non-null   int64
 1   producto     3035 non-null   object
 2   precio       3033 non-null   object
 3   cantidad     3033 non-null   float64
 4   fecha_venta  3035 non-null   object
 5   categoria    3035 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 142.4+ KB
          id_venta     cantidad
count  3035.000000  3033.000000
mean   1499.851400     6.496538
std     866.465379     3.457250
min       1.000000     1.000000
25%     748.500000     3.000000
50%    1502.000000     7.000000
75%    2249.500000     9.000000
max    3000.000000    12.000000
Shape: (3035, 6)
Columnas: Index(['id_venta', 'producto', 'precio', 'cantidad', 'fecha_venta',
       'categoria'],
      dtype='object')

--- Análisis de clientes ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 567 entries, 0 to 566
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  567 non-null    int64
 1   nombre      567 non-null    object
 2   edad        567 non-null    int64
 3   ciudad      567 non-null    object
 4   ingresos    567 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 22.3+ KB
       id_cliente        edad      ingresos
count  567.000000  567.000000    567.000000
mean   284.000000   37.940035  34668.739012
std    163.823075   10.202885  12974.531446
min      1.000000   20.000000    170.290000
25%    142.500000   30.000000  26015.240000
50%    284.000000   37.000000  35066.830000
75%    425.500000   43.000000  42457.100000
max    567.000000   81.000000  88053.010000
Shape: (567, 5)
Columnas: Index(['id_cliente', 'nombre', 'edad', 'ciudad', 'ingresos'], dtype='object')

--- Análisis de marketing ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_campanha   90 non-null     int64
 1   producto      90 non-null     object
 2   canal         90 non-null     object
 3   costo         90 non-null     float64
 4   fecha_inicio  90 non-null     object
 5   fecha_fin     90 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.3+ KB
       id_campanha      costo
count    90.000000  90.000000
mean     45.500000   4.928667
std      26.124701   0.947750
min       1.000000   2.950000
25%      23.250000   4.372500
50%      45.500000   4.900000
75%      67.750000   5.562500
max      90.000000   7.390000
Shape: (90, 6)
Columnas: Index(['id_campanha', 'producto', 'canal', 'costo', 'fecha_inicio',
       'fecha_fin'],
      dtype='object')


### 5️⃣ Calidad de Datos

Se analizan los conjuntos de datos para identificar:

- Valores nulos  
- Registros duplicados  

Se documenta el **estado inicial de los datos**, lo que permitirá tomar decisiones sobre limpieza y transformación en etapas posteriores.

In [ ]:
for nombre, df in data_frames.items():
    print(f"\n--- Análisis de {nombre} ---")
    print("Nulos:\n", df.isnull().sum())
    print("Duplicados:\n", df.duplicated().sum())

--- Análisis de ventas ---
Nulos:
 id_venta       0
producto       0
precio         2
cantidad       2
fecha_venta    0
categoria      0
dtype: int64
Duplicados:
 35

--- Análisis de clientes ---
Nulos:
 id_cliente    0
nombre        0
edad          0
ciudad        0
ingresos      0
dtype: int64
Duplicados:
 0

--- Análisis de marketing ---
Nulos:
 id_campanha     0
producto        0
canal           0
costo           0
fecha_inicio    0
fecha_fin       0
dtype: int64
Duplicados:
 0

---

# Etapa 2: Preprocesamiento y Limpieza de Datos
**Clases 5 a 8**

---

## 🎯 Objetivo
Demostrar conocimiento y aplicación de las **técnicas de limpieza, transformación, agregación e integración de datos**, fundamentales para garantizar la calidad y utilidad de la información analizada.
``

## 📌 Actividades

### 1️⃣ Limpieza de Datos

Se realiza la limpieza de los conjuntos de datos eliminando:
- Registros duplicados
- Caracteres no deseados o inconsistencias en los campos

El proceso de limpieza se documenta, comparando el estado inicial y final de los datos.

In [ ]:
#Volví a recorrer y aplique las funciones isnull() y duplicated:
for nombre, df in data_frames.items():
    print(f"\n--- Análisis de {nombre} ---")
    print("Nulos:\n", df.isnull().sum())
    print("Duplicados:\n", df.duplicated().sum())

#se eliminan los duplicados y null
for nombre, df in data_frames.items():
  print("Borrando duplicados")
  df.drop_duplicates(inplace = True)
  df.dropna(inplace=True)

  # chequeo para ver si esta ok
  for nombre, df in data_frames.items():
    print(f"\n--- Análisis de {nombre} ---")
    print("Nulos:\n", df.isnull().sum())
    print("Duplicados:\n", df.duplicated().sum())

--- Análisis de ventas ---
Nulos:
 id_venta       0
producto       0
precio         2
cantidad       2
fecha_venta    0
categoria      0
dtype: int64
Duplicados:
 35

--- Análisis de clientes ---
Nulos:
 id_cliente    0
nombre        0
edad          0
ciudad        0
ingresos      0
dtype: int64
Duplicados:
 0

--- Análisis de marketing ---
Nulos:
 id_campanha     0
producto        0
canal           0
costo           0
fecha_inicio    0
fecha_fin       0
dtype: int64
Duplicados:
 0
Borrando duplicados

--- Análisis de ventas ---
Nulos:
 id_venta       0
producto       0
precio         0
cantidad       0
fecha_venta    0
categoria      0
dtype: int64
Duplicados:
 0

--- Análisis de clientes ---
Nulos:
 id_cliente    0
nombre        0
edad          0
ciudad        0
ingresos      0
dtype: int64
Duplicados:
 0

--- Análisis de marketing ---
Nulos:
 id_campanha     0
producto        0
canal           0
costo           0
fecha_inicio    0
fecha_fin       0
dtype: int64
Duplicados:
 0
Borrando duplicados

--- Análisis de ventas ---
Nulos:
 id_venta       0
producto       0
precio         0
cantidad       0
fecha_venta    0
categoria      0
dtype: int64
Duplicados:
 0

--- Análisis de clientes ---
Nulos:
 id_cliente    0
nombre        0
edad          0
ciudad        0
ingresos      0
dtype: int64
Duplicados:
 0

--- Análisis de marketing ---
Nulos:
 id_campanha     0
producto        0
canal           0
costo           0
fecha_inicio    0
fecha_fin       0
dtype: int64
Duplicados:
 0
Borrando duplicados

--- Análisis de ventas ---
Nulos:
 id_venta       0
producto       0
precio         0
cantidad       0
fecha_venta    0
categoria      0
dtype: int64
Duplicados:
 0

--- Análisis de clientes ---
Nulos:
 id_cliente    0
nombre        0
edad          0
ciudad        0
ingresos      0
dtype: int64
Duplicados:
 0

--- Análisis de marketing ---
Nulos:
 id_campanha     0
producto        0
canal           0
costo           0
fecha_inicio    0
fecha_fin       0
dtype: int64
Duplicados:
 0


### 2️⃣ Transformación de Datos

Se aplican filtros y transformaciones para crear una nueva tabla de ventas que muestre únicamente los **productos de alto rendimiento**, definidos en base a criterios como volumen de ventas o ingresos generados.

In [ ]:
# Se crea columna nueva y se calcula total por venta:
df_ventas['total_venta'] = df_ventas['precio'].str.replace('$', '', regex=False).astype(float) * df_ventas['cantidad']


### 3️⃣ Agregación de Datos

Se resumen las ventas agrupando por **categoría de producto**, permitiendo analizar:
- Ingresos totales
- Cantidad vendida por categoría

Este paso facilita la identificación de patrones y categorías más relevantes.

In [ ]:
# ingreso por producto:

# Se crea columna nueva y se calcula total por venta:
df_ventas['total_venta'] = df_ventas['precio'].str.replace('$', '', regex=False).astype(float) * df_ventas['cantidad']

df_ventas.head()

#se crea la pivot table
ingreso_por_producto = pd.pivot_table(
    df_ventas,
    values = ['total_venta'],
    index = ['categoria'],
    aggfunc=sum
)

ingreso_por_producto.head()

#cantidad por categoria:
cantidad_por_categoria = pd.pivot_table(
    df_ventas,
    values = ['cantidad'],
    index = ['categoria'],
    aggfunc = 'sum'
)

cantidad_por_categoria.head()

/tmp/ipykernel_658/226578948.py:8: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  ingreso_por_producto = pd.pivot_table(

                   cantidad
categoria
Decoración           6490.0
Electrodomésticos    6592.0
Electrónica          6413.0


### 4️⃣ Integración de Datos

Se combinan los conjuntos de datos de **ventas** y **marketing** utilizando claves comunes, con el objetivo de obtener una visión más amplia de las tendencias y el impacto de las acciones comerciales sobre las ventas.

In [ ]:
#df_marketing.head()

#primero agrupo ventas:

ventas_resumidas = df_ventas.pivot_table(
    values='total_venta',
    index='producto',
    aggfunc='sum'
).reset_index()


df_combinado = pd.merge(
    ventas_resumidas,
    df_marketing,
    on=['producto'],
    how='inner'
)

#df_combinado['roi'] = df_combinado['total_venta'] / df_combinado['costo']

df_combinado.head()

,producto,total_venta,id_campanha,canal,costo,fecha_inicio,fecha_fin,roi
0,Adorno de pared,48093.49,74,TV,4.81,20/03/2024,03/05/2024,9998.646570
1,Adorno de pared,48093.49,44,Email,5.08,13/04/2024,10/05/2024,9467.222441
2,Adorno de pared,48093.49,14,RRSS,4.16,22/10/2024,21/12/2024,11560.935096
3,Alfombra,44773.06,58,Email,4.25,31/03/2024,05/05/2024,10534.837647
4,Alfombra,44773.06,88,TV,7.39,25/07/2024,31/08/2024,6058.600812